[project]
name = "wibt-tool"
dynamic = ["version"]
requires-python = ">= 3.14"
dependencies = [
  "dotenv",
  "requests",
  "openai",
  "marimo",
  "altair",
  "pandas",
  "pyarrow"
]

[tool.marimo.runtime]
pythonpath = ["src"]
